DefaultContentLanguage = "en"
baseURL = "https://www.carlpearson.net/"
languageCode = "en"
title = "Website of Carl Pearson"

theme = "anatole"

enableEmoji = true
enableRobotsTXT = true
summarylength = 10

# Enable Disqus
#disqusShortname = ""

# Google Analytics
# googleAnalytics = "UA-54975774-2"

# Syntax highlighting
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
