DefaultContentLanguage = "en"
baseURL = "https://www.carlpearson.net/"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
summarylength = 10
theme = "anatole"
title = "Website of Carl Pearson"

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-54975774-2"

# Syntax highlighting
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[params]
author = "Carl Pearson"
title = "Carl Pearson"
# copyright = "2020-2021"
description = "Postdoctoral Appointee, Sandia National Labs and Research Assistant Professor, University of New Mexico CS. All opinions are my own."
favicon = "favicons/"
keywords = ""
profilePicture = "img/avatar.jpg"
# example ["css/custom.css"]
# added css/syntax.css after hugo gen chromastyles --style=mannai > assets/css/syntax.css
customCss = ["css/custom.css", "css/syntax.css"]
# customCss = []
# example ["js/custom.js"]
customJs = []
doNotLoadAnimations = true
images = ["img/bubbles.jpg"]
mainSections = ["publication"]
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex" # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/cwpearson/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/cwpearson"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:cwpears@sandia.gov"

[[params.socialIcons]]
icon = "fas fa-university"
title = "Google Scholar"
url = "https://scholar.google.com/citations?user=K2nzqpYAAAAJ&hl=en"

## Menu items

[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 100

[[menu.main]]
identifier = "publications"
name = "Publications"
url = "/publication/"
weight = 300

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/project/"
weight = 400

[[menu.main]]
identifier = "awards"
name = "Recognition"
url = "/awards/"
weight = 500

[[menu.main]]
identifier = "experience"
name = "Experience"
url = "/experience/"
weight = 600

[[menu.main]]
identifier = "talks"
name = "Talks"
url = "/talk/"
weight = 700

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/post/"
weight = 800
