DefaultContentLanguage = "en"
baseURL = "https://www.carlpearson.net/"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
summarylength = 10
theme = "anatole"
title = "Website of Carl Pearson"

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-54975774-2"

# Syntax highlighting
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
