# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "Carl Pearson"

# The URL of your website.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://cwpearson.github.io/"

# Your copyright notice - appears in site footer.
# To display a copyright symbol, type `&copy;`.
copyright = "&copy; 2019 Carl Pearson"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-54975774-2"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Name of Academic theme folder in `themes/`.
theme = "academic"

# Get last modified date for content from Git?
enableGitInfo = false

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]




# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

# Get last modified date for content from Git?
enableGitInfo = false

[outputs]
  home = [ "HTML", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
author = "authors"


[params]
  # AUTHOR SETUP

  # Your details.
  name = "Carl Pearson"
  role = "PhD Candidate"

  # Organizations/Affiliations.
  #   Separate multiple entries with a comma, using the form: `[ {name="Org1", url=""}, {name="Org2", url=""} ]`.
  organizations = [ { name = "University of Illinois Urbana-Champaign", url = "http://www.ece.illinois.edu/" } ]

  
  avatar = "headshot.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.




  # SITE SETUP


  # Show estimated reading time for posts?
  reading_time = false

  # Display comment count? Requires commenting to be enabled.
  comment_count = true

  # Display next/previous section pager?
  section_pager = false



  highlight_languages = []
  # highlight_style = "github"




  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multilingual sites, `publication_types` can be copied to each language section at the end of this file and
  #   translated.
  publication_types = [
    'Uncategorized',  # 0
    'Conference paper',  # 1
    'Journal article',  # 2
    'Manuscript',  # 3
    'Report',  # 4
    'Book',  # 5
    'Book section'  # 6
  ]

  # Configuration of talk pages.
  [params.talks]
    # Show talk time?
    time = true

  # Configuration of publication pages.
  [params.publications]
    # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "January, 2006"

  # Configuration of project pages.
  [params.projects]
    # List publications and talks related to the project?
    list_children = true

    # Post list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = Stream
    post_format = 2

    # Publication list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = APA
    #   3 = MLA
    #   4 = Stream
    publication_format = 4

    # Talk list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = Stream
    talk_format = 2

  # Social/Academic Networking
  #
  # Icon pack "fab" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fas" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fontawesome.com/icons
  #
  # Icon pack "ai" includes the following academic icons:
  #
  #   cv, google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fas"
    link = "mailto:pearson@illinois.edu"  # For a direct email link, use "mailto:test@example.org".

  # [[params.social]]
  #   icon = "twitter"
  #   icon_pack = "fab"
  #   link = "https://twitter.com/GeorgeCushen"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=K2nzqpYAAAAJ"

  [[params.social]]
    icon = "github"
    icon_pack = "fab"
    link = "https://github.com/cwpearson"

  # Link to a PDF of your resume/CV from the About widget.
  # To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
  # [[params.social]]
  #   icon = "cv"
  #   icon_pack = "ai"
  #   link = "files/cv.pdf"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
[params.menus]
  # Align the main menu to the right of the page? (true/false)
  align_right = true




# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[menu.main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 7

# Search.
[params.search]
  # Search provider:
  #   0: No search engine
  #   1: Built-in (Fuse)
  #   2: Algolia (https://www.algolia.com)
  engine = 1

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [params.search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"

# Uncomment the lines below to configure your website in a second language.
#[languages.zh]
#  languageCode = "zh-Hans"
#  title = "Chinese website title..."
#  [languages.zh.params]
#    name = "Your name in Chinese..."
#    role = "Your role in Chinese..."
#  [[languages.zh.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1



