baseURL = "https://carlpearson.net"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Carl Pearson"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-54975774-2"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Carl Pearson"
author = "Carl Pearson"
# copyright = "2020-2021"
description = "University of Illinois ECE PhD Student"
profilePicture = "img/avatar.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["publication"]
images = ["img/bubbles.jpg"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "mathjax"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = ""

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/cwpearson"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:pearson@illinois.edu"

[[params.socialIcons]]
icon = "fas fa-university"
title = "Google Scholar"
url = "https://scholar.google.com/citations?user=K2nzqpYAAAAJ&hl=en"


## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Recognition"
  weight = 200
  identifier = "awards"
  url = "/awards/"

  [[menu.main]]
  name = "Experience"
  weight = 200
  identifier = "experience"
  url = "/experience/"

  [[menu.main]]
  name = "Publications"
  weight = 300
  identifier = "publications"
  url = "/publication/"

  [[menu.main]]
  name = "Posts"
  weight = 400
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Projects"
  weight = 500
  identifier = "projects"
  url = "/project/"
