
author = "Carl Pearson"
title = "Carl Pearson"
#copyright = "2020-2021"
description = "Postdoctoral Appointee, Sandia National Labs and Research Assistant Professor (LAT), University of New Mexico CS. All opinions are my own."
favicon = "favicons/"
keywords = ""
profilePicture = "img/avatar.png"
# example ["css/custom.css"]
# added css/syntax.css after hugo gen chromastyles --style=mannai > assets/css/syntax.css
# added katex css
customCss = ["css/custom.css", "css/syntax.css", "css/katex.css"]
# example ["js/custom.js"]
# added katex js
customJs = ["js/katex.js", "js/auto-render.js"]
doNotLoadAnimations = true
images = ["images/site-feature-image.png"]
mainSections = ["post"]
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
googleSiteVerify = "U9IpipB53J4-oqOojG29IDCgopThWA-fegNu76eJPtE"
indexDateFormat = "1/2/2006"
listDateFormat = "1/2/2006"
singleDateFormat = "1/2/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
id = "396fc01e-d393-4b58-b529-7a6ebafc1ed8"
serverURL = "analytics.carlpearson.net"

## Math settings
[math]
enable = false # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex" # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/cwpearson/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/cwpearson"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:cwpears@sandia.gov"

[[socialIcons]]
icon = "fas fa-university"
title = "Google Scholar"
url = "https://scholar.google.com/citations?user=K2nzqpYAAAAJ&hl=en"
