dist: trusty

install:
  - wget -q https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz -O hugo.tar.gz
  - tar -xvf hugo.tar.gz
  - mkdir -vp ~/bin
  - mv -v hugo ~/bin/hugo
  - export PATH="$HOME/bin:$PATH"

script:
  - hugo version
  - hugo

after_success: |
  set -e
  if [ -n "$GITHUB_TOKEN" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
    cd "$TRAVIS_BUILD_DIR"
    cd public
    git init
    git checkout -b master
    git add .
    git -c user.name='cwpearson' -c user.email='carl.w.pearson@gmail.com' commit -m "push from hugo-cwpearson $TRAVIS_COMMIT"
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://cwpearson:$GITHUB_TOKEN@github.com/cwpearson/cwpearson.github.io master 2> /dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
  set +e
