dist: trusty

install:
  - snap install hugo

script:
  - hugo

after_success: |
  if [ -n "$GITHUB_TOKEN" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `web` directory containing the website.
    cd public
    git init
    git checkout -b master
    git add .
    git -c user.name='cwpearson' -c user.email='carl.w.pearson@gmail.com' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://cwpearson:$GITHUB_TOKEN@github.com/cwpearson/cwpearson.github.io master &2> /dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
